name: GitHub Actions Demo test
on: [push,fork,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  
    steps:
    - name: RazDvaTri
      run: pwd

#     - name: Slack Notification
#       uses: ravsamhq/notify-slack-action@v2
#       if: always()
#       with:
#         status: ${{ job.status }} # required
#       env:
#         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    
    - name: toJson
      run: echo "${{ toJson(github) }}"
      
    - name: Slack notification
      uses: ravsamhq/notify-slack-action@v2
      if: always()
      with:
        status: ${{ job.status }}
        token: ${{ secrets.GITHUB_TOKEN }}
        notification_title: "{workflow} has {status_message}"
        message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> \n ${{ github.ref }} \n ${{ github.head_ref }}"
        footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
  
